export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const RENTAL_REPOSITORY = 'RENTAL_REPOSITORY';
export const BUSINESS_CODE_REPOSITORY = 'BUSINESS_CODE_REPOSITORY';
export const HOUSING_REG_INFO_REPOSITORY = 'HOUSING_REG_INFO_REPOSITORY';
