version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql